### ISSUE TITLE
Python tensorflow Version 

### ISSUE THREAD

**Issue by ZLKong** [tkazusa/CVAE-GAN#2]
Hi,
Can you tell me the Python and Tensorflow version that you ran on?
Thank you very much!

**Comment by zhouying3** [comment]
python 3.5.4
tensorflow 1.4.0
| |
zhouying
|
|
zhouying_rita@163.com
|
签名由网易邮箱大师定制
On 9/11/2018 04:04，ZLKong<notifications@github.com> wrote：

Hi,
Can you tell me the Python and Tensorflow version that you ran on?
Thank you very much!

**Comment by ZLKong** [comment]
Thank you!

**Comment by zhouying3** [comment]
it's a class similar to the Dataset in mnist in tensorflow.

2018-09-18 

zhouying_rita 



发件人：ZLKong <notifications@github.com>
发送时间：2018-09-11 21:20
主题：Re: [tkazusa/CVAE-GAN] Python tensorflow Version (#2)
收件人："tkazusa/CVAE-GAN"<CVAE-GAN@noreply.github.com>
抄送："zhouying3"<442049887@qq.com>,"Comment"<comment@noreply.github.com>

Thank you!
